### ISSUE TITLE
Getting error with list_changed_files setting

### ISSUE THREAD

**Issue by bhutkovskyysos** [telia-oss/github-pr-resource#133]
I am using latest Concourse 5.3.0. When trying to add `list_changed_files: true` I get the following error:

```
2019/07/18 19:32:02 failed to unmarshal request: json: unknown field "list_changed_files"
```

I tried adding it to the resource:

```
- name: pull-request
  type: pull-request
  check_every: 1m
  webhook_token: ((webhook-token))
  source:
    list_changed_files: true
    repository: my/repo
    access_token: ((git_access_token))
    v3_endpoint: https://api.github.com
    v4_endpoint: https://api.github.com/graphql
    base_branch: master
```

or via params but still the same error occurs.
