### ISSUE TITLE
"list_changed_files: true" giving error with latest tag

### ISSUE THREAD

**Issue by Mounikak1** [telia-oss/github-pr-resource#138]
I am using concourse v3.13.0, I am getting error while using list_changed_files setting.
Here is resource config, let me know if I am missing anything
```
-  name: Repo
   type: pull-request
   check_every: 1m
   source:
      v3_endpoint: ((github_api))
      v4_endpoint: ((github_api_v4))
      access_token: ((git_access_token))
      repository: ((git_repo))
      base_branch: ((branch))
      list_changed_files: true
```
**error is following**
```resource script '/opt/resource/check []' failed: exit status 1

stderr:
2019/08/06 00:09:32 failed to unmarshal request: json: unknown field "list_changed_files" ```
