### ISSUE TITLE
Extremely high V3 API usage when using paths filtering

### ISSUE THREAD

**Issue by YenTheFirst** [telia-oss/github-pr-resource#142]
Given (1) a github repo with two files:

    - frequently_updated_file.txt
    - rarely_updated_file.txt

and (2) a resource that is configured to emit new versions of PRs that modify rarely_updated_file.txt:
```
- name: pr-branch
  type: pull-request
  source:
    access_token: ((github-token))
    paths:
    - rarely_updated_file.txt
    repository: example-user/example-repo
```

and (3) a large number (30+) of open PRs affecting `frequently_updated_file.txt`, but not `rarely_updated_file.txt`,

then, every instance of a `check` of this resource will result in a very large number of V3 API calls. These calls seem to specifically be related to checking for modified files, https://github.com/telia-oss/github-pr-resource/blob/master/github.go#L181. Adding a debug line after this response indicates the `response.Rate` decrementing multiple times per `check`

We've run in to this issue when trying to use this resource-type on several pipelines for projects that live in a monorepo, which use `paths:` to limit to PRs that affect a certain pipeline's project. Rarely updated projects end up continually re-polling _every_ unrelated new PR to check for modifications.

This seems thorny, and I'm not sure how to work around it, short of emitting occasional "fake" versions that the downstream pipeline would need to check for and ignore. It seems like a problem with Concourse's resource API design?
