### ISSUE TITLE
Some PRs are missing from check

### ISSUE THREAD

**Issue by mattdodge** [telia-oss/github-pr-resource#150]
We've been running this resource for a few weeks now with mostly great success. However, I have noticed that there is a small number of PRs in our repo that don't seem to get picked up. We've closed the PR and re-opened new ones and they still don't appear even though other PRs are getting picked up.

We don't (knowingly) have any kind of exclusion rules, here's the relevant YML for our pipeline:
```yml
resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: my-pr
    type: pull-request
    icon: github-circle
    check_every: 3m
    webhook_token: "((github_access.WEBHOOK_SECRET))"
    source:
      repository: myorg/myrepo
      access_token: "((github_access.GITHUB_ACCESS_TOKEN))"

jobs:
  - name: deploy
    plan:
      - get: my-pr
        trigger: true
        version: every
```

I've looked at the concourse worker logs and don't see anything weird there either. What's the best next step for troubleshooting?
