### ISSUE TITLE
How does `rebase` strategy actually work?

### ISSUE THREAD

**Issue by leshik** [telia-oss/github-pr-resource#153]
I have my job configured like this:

```yaml
jobs:
- name: test-pull-request
  plan:
  - get: myproject
    version: every
    trigger: true
    params:
      git_depth: 100
      integration_tool: rebase
      …
  - task: Test pull request
      inputs:
      - name: myproject
      …
```

What I thought would be done is that it rebases the pull against master and then runs the task on it. At first glance it looks like it does exactly this:

```
author | leshik
base_name | master

First, rewinding head to replay your work on top of it...
Applying: Testing `rebase` strategy
```

But then the task fails because it lacks changes present in master, and checking the input content with `fly hijack` confirms that the branch in question isn't rebased in fact.

What am I missing?
