### ISSUE TITLE
put: pull-request removes .git/resource/changed_files

### ISSUE THREAD

**Issue by gdamjan** [telia-oss/github-pr-resource#155]
when you have a pr resource with `params:  {list_changed_files: true}` and you only have a plan with `get` and then `task`, in the task you get the `.git/resource/changed_files` (introduced in 0.17). 

But, if there's a `put: ` action between the get and task (typically with `params: { status: pending }`, the `.git/resource/changed_files` is then missing in the `task` action.

**Comment by itsdalmo** [comment]
Hey @gdamjan and thanks for the issue! I think perhaps the implicit `get` after `put` in Concourse is what might be the root problem for you here, and I think the following workaround can help you (read more about it in README.md):

```yaml
put: update-status <-- Use an alias for the pull-request resource
resource: pull-request
params:
    path: pull-request
    status: pending
get_params: {skip_download: true}
```
