### ISSUE TITLE
Subsequent changes to PR branches weren't picked up

### ISSUE THREAD

**Issue by mattgodbolt** [telia-oss/github-pr-resource#162]
I'm using GH Enterprise, and trying to anything other than the initial build for a PR working.

```
  - name: pull-request
    type: pull-request
    check_every: 1m
    source:
      v3_endpoint: https://ELIDED/api/v3
      v4_endpoint: https://ELIDED/api/graphql
      repository: aquatic/research
      access_token: ((concourse.github-access-token))
```

and...

```
    plan:
      - get: research
        resource: pull-request
        trigger: true
        version: every
      - put: pull-request
        params:
          path: research
          status: pending
      - in_parallel:
          - task: run-unit-tests
            file: research/concourse/make_test.yml
          - task: run-integration-tests
            file: research/concourse/make_integration.yml
```

I create a PR and it gets picked up and built. But subsequent changes are ignored. I can force a check on `pull-request` but the UI indicates only the first SHA:

View of the source:

![Screenshot from 2019-11-05 15-34-28](https://user-images.githubusercontent.com/633973/68248200-faaee080-ffe1-11e9-966e-a5cb8827ed33.png)

View in GH:

![Screenshot from 2019-11-05 15-36-12](https://user-images.githubusercontent.com/633973/68248287-229e4400-ffe2-11e9-94e2-cf31a57f9505.png)

If I manually try and build the step it wedges in "preparing build" with spinny wheels in:

```
discovering any new versions of research
waiting for a suitable set of input versions
research - checking for latest available versions
```

Any ideas what I might be doing wrong here?
