### ISSUE TITLE
Name clash while using the same name for resource and resource type

### ISSUE THREAD

**Issue by bbodensieck** [telia-oss/github-pr-resource#175]
When trying the example https://github.com/telia-oss/github-pr-resource#example we discovered a problem by using the same name for resource and resource type. We are using concourse `v5.6.0`.

We got a `Error 500: base resource type not found: pull-request`

Seems that there is a name clash. After renaming the resource_type to e.g. `pull-request-resource` it worked.

*Before*
```
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: pull-request
  type: pull-request
  check_every: 24h
  webhook_token: ((webhook-token))
  source:
    repository: itsdalmo/test-repository
    access_token: ((github-access-token))
```

*After*
```
resource_types:
- name: pull-request-resource
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: pull-request
  type: pull-request-resource
  check_every: 24h
  webhook_token: ((webhook-token))
  source:
    repository: itsdalmo/test-repository
    access_token: ((github-access-token))
```
Could you update the example please?
