### ISSUE TITLE
return value 32 - meaning

### ISSUE THREAD

**Issue by drahnr** [telia-oss/github-pr-resource#182]
Using this resource coming from `jtarchie/pull-request` I always get this error

```
resource script '/opt/resource/in [/tmp/build/get]' failed: exit status 32
```

recreating the token or even restarting the worker did not change anything.

The (simplified) concourse yml is:

```
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: pr-juice
  type: pull-request
  check_every: 10m
  source:
    repository: spearow/juice
    access_token: ((magictoken))

jobs:
  - name: pr-test-juice
    build_logs_to_retain: 4
    public: true
    serial: true
    plan:
    - in_parallel:
      - get: rust-cudnn
      - get: rust-blas
      - get: rust-cublas
      - get: pr-juice
        verision: every
        trigger: true

      - get: container-fedora-cuda
        trigger: true

    - put: pr-juice-stat
      resource: pr-juice
      params:
        path: pr-juice
        status: pending
    - task: build-fedora-build
      image: container-fedora-cuda
      config:
        platform: linux
        inputs:
        - name: rust-cudnn
        - name: rust-blas
        - name: rust-cublas
        - name: pr-juice
        caches:
        - path: target
        run:
          path: sh
          args:
          - -exc
          - |
            cargo build
          dir: pr-juice

      on_failure:
        put: pr-juice-stat
        resource: pr-juice
        params:
          path: pr-juice
          status: failure

    - task: build-fedora-test
      image: container-fedora-cuda
      config:
        platform: linux
        inputs:
        - name: rust-cudnn
        - name: rust-blas
        - name: rust-cublas
        - name: pr-juice
        caches:
        - path: target
        run:
          path: sh
          args:
          - -exc
          - |
            cargo t
          dir: pr-juice

      on_failure:
        put: pr-juice-stat
        resource: pr-juice
        params:
          path: pr-juice
          status: failure

    - put: pr-juice-stat
      resource: pr-juice
      params:
        path: pr-juice
        status: success

```
