### ISSUE TITLE
404 setting status with GitHub Enterprise

### ISSUE THREAD

**Issue by tvon** [telia-oss/github-pr-resource#191]
Working off of the pipeline example in the `README`, I have it configured for GHE:

```yaml
resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: pull-request
    type: pull-request
    check_every: 24h
    webhook_token: eightchr-four-four-four-twelvethings
    source:
      repository: concourse/uberforcats
      v3_endpoint: https://git.example.com/api/v3
      v4_endpoint: https://git.example.com/api/graphql
      access_token: ((github_token))

```

The check works and successfully finds the test pull request.

The `put: pull-request` errors with a 404:

```
2020/03/21 13:23:49 put failed: failed to set status: POST https://git.example.com/api/v3/repos/concourse/uberforcats/statuses/1ee33c4d41fc5dd89249c414943407b4d3831ea6: 404 Not Found []
```

Using `fly intercept` I can `curl` a `POST` to that endpoint without issue:

```
$ fly -t concourse intercept -u https://concourse.example.com/teams/concourse/pipelines/uberforcats/jobs/test/builds/2 sh
tmp/build/put # 
# omit installing curl
tmp/build/put # export GITHUB_OAUTH_TOKEN="astringoffortyrandomlettersandnumbersbro"
tmp/build/put # curl --data '{"state": "success"}' -H "Authorization: token ${GITHUB_OAUTH_TOKEN}" https://git.example.com/api/v3/repos/concourse/uberforcats/statuses/1ee33c4d41fc5dd89249c414943407b4d3831ea6
{
  # json success bits
}
```

If I understand correctly the `check` and `in` use the `graphql` endpoint, but the `out` uses the `v3` endpoint.  I would think I might have misconfigured it except the URL printed in the error works with `curl`.

Concourse v5.8.0, running in Azure in a private network with various firewalls which may be the culprit but then curl and the `check`/`in` work so that seems less likely.
