### ISSUE TITLE
Trigger downstream job only when it has a label

### ISSUE THREAD

**Issue by ArjanSchouten** [telia-oss/github-pr-resource#209]
Is it possible with github-pr-resource to trigger downstream jobs on a specific label?

I was wondering if something like this is possible:
```
- name: PR:build-and-test
  plan:
  - get: pr-source
     trigger: true
     version: every
- name: PR:e2e-test
  plan:
    - in_parallel:
        - get: pr-source
          trigger: true
          params:
            labels: ["e2e"]
          passed:
            - PR:build-and-test
```

**Comment by asummers** [comment]
From [the README](https://github.com/telia-oss/github-pr-resource#source-configuration):

> labels
> The labels on the PR. The pipeline will only trigger on pull requests having at least one of the specified labels.

So you'd define the labels on the resource itself like:

```
- name: pull-request-with-label
  type: pull-request
  source:
    labels: ["e2e"]
    ...

jobs:
- name: test
  plan:
  - get: pull-request-with-label
    trigger: true
    ...
```
