### ISSUE TITLE
handling merge conflicts - guideline

### ISSUE THREAD

**Issue by drahnr** [telia-oss/github-pr-resource#210]
In https://github.com/telia-oss/github-pr-resource/issues/76 it is suggested that one uses the `on_failure` to report i.e. merge conflicts, but that resolves only in errors regarding missing `version.json`

```text
2020/06/17 07:05:47 put failed: failed to read version from path: open /tmp/build/put/git-pull-request-resource/.git/resource/version.json: no such file or directory
```

```yaml
resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: git-pull-request-resource
  type: pull-request
  source:
    repository: drahnr/cargo-spellcheck
    access_token: ((token))

jobs:
  - name: pr-validate
    build_logs_to_retain: 10
    public: true
    serial: true
    plan:
    - put: git-pull-request-resource
      params:
        path: git-pull-request-resource
        context: meta-check
        status: pending

    - get: git-pull-request-resource
      resource: git-pull-request-resource
      trigger: true
      on_success:
        put: git-pull-request-resource
        params:
          path: git-pull-request-resource
          context: merge-conflict
          status: success
      on_failure:
        put: git-pull-request-resource
        params:
          path: git-pull-request-resource
          context: merge-conflict
          status: failure


```

![image](https://user-images.githubusercontent.com/667047/84867959-3c296300-b07c-11ea-9c10-5d31986f9e2a.png)

https://ci.spearow.io/teams/main/pipelines/cargo-spellcheck/jobs/pr-validate/builds/23

**Comment by itsdalmo** [comment]
It seems you are attempting to `put` a status before using `get` on the resource, which means `version.json` is not populated/you get an error. Take a look at the [example in the README](https://github.com/telia-oss/github-pr-resource#example) and hopefully it should work for you 👍

**Comment by drahnr** [comment]
The issue here is, that even with

```yaml
    - get: git-pull-request-resource
      resource: git-pull-request-resource
      version: every
      trigger: true
      on_success:
        put: git-pull-request-resource
        params:
          path: git-pull-request-resource
          context: merge-conflict
          status: success
      on_failure:
        put: git-pull-request-resource
        params:
          path: git-pull-request-resource
          context: merge-conflict
          status: failure
```

![image](https://user-images.githubusercontent.com/667047/84871789-41d57780-b081-11ea-85e6-223a66cea8d1.png)


still fails with the same issue, since the get step fails - which leaves the question on how to report merge conflicts back still open.
