### ISSUE TITLE
allow to pass multiple contexts:

### ISSUE THREAD

**Issue by drahnr** [telia-oss/github-pr-resource#214]
# Context

I would prefer to have some more fine granular display in github what is pending what has succeeded in a bigger workspace project.

# Currently

Roughly 30 sequential or parallel containers need to be spawn just for setting all the checks to be pending.

```
# ~30x
    - put: pr-juice-stat
      resource: pr-juice
      params:
        path: pr-juice
        context: coaster-blas-{{ backend.execute }}-{{ testenv.name }}-{{ backend }}
        status: pending
```

# Wish

Being able to run
```
    - put: pr-juice-stat
      resource: pr-juice
      params:
        path: pr-juice
        context: [
# ~30x items
coaster-blas-{{ backend.execute }}-{{ testenv.name }}-{{ backend }},
coaster-nn-{{ backend.execute }}-{{ testenv.name }}-{{ backend }},
]
        status: pending
```
