### ISSUE TITLE
failed to fetch digest for image 'teliaoss/github-pr-resource:latest': 429 Too Many Requests

### ISSUE THREAD

**Issue by 0x001f** [telia-oss/github-pr-resource#242]
I am always grateful to the contributors.

## What happened?

1. We have confirmed that `teliaoss/github-pr-resource: latest` in the Docker registry fails `check` due to the rate limit of docker pull.

## What is the expected result?

1. It would be helpful if you could apply to Docker that "teliaoss/github-pr-resource" is an OSS project so that it is not subject to the docker pull rate limit.

Reference information : [Expanded Support for Open Source Software Projects](https://www.docker.com/blog/expanded-support-for-open-source-software-projects/)

## How to reproduce it?

### Pipeline definition

```yaml
---
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

- name: pull-request
  type: pull-request
  check_every: 1m
  source:
    repository: {{GIT_REPOSITORY}}
    base_branch: main
    access_token: ((GIT_ACCESS_TOKEN))

jobs:
- name: test-job
  plan:
  - get: pull-request
    trigger: true
    version: every
  ...
```

### Web UI

```text
run check step: run check step: find or create container: fetching the image did not produce a volume
```

###  CLI 

```console
fly -t ci check-resource-type -r <PIPELINE_NAME>/pull-request
```

```text
id    name          status   check_error                                                                                                                                                                                                                       
xxxx  pull-request  errored  run check step: run check step: check: resource script '/opt/resource/check []' failed: exit status 1

stderr:
failed to fetch digest for image 'teliaoss/github-pr-resource:latest': 429 Too Many Requests
does the image exist?
```

Thank you for providing nice features in OSS.
