### ISSUE TITLE
No build triggered if base branch is changed

### ISSUE THREAD

**Issue by Donnerbart** [telia-oss/github-pr-resource#266]
We have a simple PR builder pipeline like this:
```
resource_types:

  - name: pull-request
    type: registry-image
    source:
      repository: teliaoss/github-pr-resource

resources:

  - name: my-repo-source
    icon: github
    type: pull-request
    source:
      repository: my-org/my-repo
      access_token: ((my-org-github-api-token))
```

We just removed our `base_branch: main` configuration to enable builds on all PRs, including ones which are based onto a release branch. But when I change the base branch on an existing PR, no build is triggered. I have to push a new commit or rebase and force push to the branch, to trigger a new build.

Can someone confirm this?

Is this something this resource should or can handle? Or is the issue that GitHub doesn't seem to remove the previous checks when the base branch is changed?
