### ISSUE TITLE
Could the PR remain in branch instead of merged to master?

### ISSUE THREAD

**Issue by pivotal-bin-ju** [telia-oss/github-pr-resource#268]
I tried to set `integration_tool=checkout`, but the branch code is still merged to master. I am wondering if there a way to leave the PR in the branch?

I know the old `jtarchie` works in this flavor, the new resource break our pipeline.

Thanks!

**Comment by tremblaysimon** [comment]
If you use a put step, you must use get_params to add integration_tool=checkout parameter otherwise it will be override by the implicit get step done after a put step.

It looks like this in one of my job: 

```yaml
...
    - get: pull-request
    - put: pull-request
      params:
        status: pending
        path: pull-request
      get_params:
        integration_tool: checkout
...
```
