### ISSUE TITLE
Github status not updated for ignored paths

### ISSUE THREAD

**Issue by ejgreco** [telia-oss/github-pr-resource#288]
Hey there,

We are using the github-pr-resource quite heavily in our pipeline. We've come across an issue where the github status of checks where the path that is not valid is not being updated, stuck in ```expected``` state. For instance, we have this configuration:
```
resources:
- check_every: 5m
  name: pr_app
  source:
    access_token: TOKEN
    paths:
    - app/
    - gradle/
    repository: org/repo
  type: github-pr-resource
```
When a PR comes with files changed in the ```app/``` and ```gradle/``` folder, the tests run and statuses are updated. But if a PR runs with files changed in other folders, the statuses stay in the ```expected``` state.

The same is also true for the ```ignore_paths``` config as well:

```
resources:
- check_every: 5m
   name: ignore_paths_app
   source:
     access_token: TOKEN
     ignore_paths:
     - app/
     repository; org/repo
  type: github-pr-resource
```
If files changed on a PR are in the ```app/``` folder, the statuses are not updated. If any other folder is changed, it runs fine.

I've tried destroying and recreating the pipeline from Concourse yml. I looked at the logs for Concourse but these jobs that are supposed to sjipdon't even exist in the logs when they're missed. I've also tried renaming the resource, then reverting to the original name since the current resource names are intertwined in our build scripts. I also version bumped our usage of the ```github-pr-resource``` from ```v0.21.0``` to ```v0.23.0```.

Any help is appreciated!
