### ISSUE TITLE
Cant update github commit status when merge conflicts are generated

### ISSUE THREAD

**Issue by scottillogical** [telia-oss/github-pr-resource#308]
Pretty much same as #210,
Given I the following pipeline setup, with a get step using the default integration_tool strategy of merge and then a put step on failure/error using the same PR resource:

  ```
on_error:
    get_params:
      skip_download: true
    params:
      comment: build errored! $ATC_EXTERNAL_URL/teams/main/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
      path: cheetah
      status: error
    put: cheetah-update
    resource: prs
  on_failure:
    get_params:
      skip_download: true
    params:
      comment: build failed! $ATC_EXTERNAL_URL/teams/main/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
      path: cheetah
      status: failure
    put: cheetah-update
    resource: prs
  on_success:
    get_params:
      skip_download: true
    params:
      path: cheetah
      status: success
    put: cheetah-update
    resource: prs
plan:
  - get: cheetah
    params:
      integration_tool: checkout
    resource: prs
    trigger: true
```

And given you have a merge conflict on this branch, the put notification will generate

`2025/02/04 17:29:27 put failed: failed to read version from path: open /tmp/build/put/cheetah/.git/resource/version.json: no such file or directory`
