### ISSUE TITLE
git failed: exit status 128

### ISSUE THREAD

**Issue by TG-KK** [telia-oss/github-pr-resource#35]
Till now I was using jtarchie's pr resource, as that image has git username param. Whenever I used telia-oss version, I got the below error in the resource check itself:

```shell
Initialized empty Git repository in /tmp/build/get/.git/
2018/08/27 22:00:34 get failed: exit status 128
```

[SO says](https://stackoverflow.com/a/17228373/10193289) it could be due to missing username and email, and indeed the error disappeared when I used jtarchie's resource along with username param.

But now, since he's retiring his resource(#34),  I think we need to add username param into this resource as well.

**Comment by itsdalmo** [comment]
Hey! Could you include a trimmed down version of your pipeline definition, or just the part that shows your source configuration for the resource?

**Comment by jtarchie** [comment]
@itsdalmo, they are referring to the fact that basic auth can be used with an `https` checkout. This is something that some Github Enterprise setups do.

**Comment by itsdalmo** [comment]
Thanks @jtarchie! The resource should already use https for the `pull` and `fetch`, and [includes the `access_token`](https://github.com/telia-oss/github-pr-resource/blob/master/git.go#L127-L132) from the source configuration as described [here](https://platform.github.community/t/git-clone-access-with-an-installation-token/486/2) so that we essentially end up with `git pull https://x-access-token:<access_token>@<repo-uri>` (and the URI is not specified by the user but retrieved from the Github API). Since the `access_token` is used to clone the repository it also needs read access for repository contents, which _should_ make the `username` and `password` unnecessary. 

@TG-KK - Did your source configuration look a little something like the example below when using `teliaoss/github-pr-resource`?

```yml
    resource_types:
    - name:                      pull-request
      type:                      docker-image
      source:
        repository:              teliaoss/github-pr-resource
        tag:                     latest

  resources:
    - name:                      pr-code
      type:                      pull-request
      source:
        repository:              my_org/code_repo
        access_token:            ((ci.personal_access_token))
        v3_endpoint:             https://github.mycompany.com/api/v3/
        v4_endpoint:             https://github.mycompany.com/api/v4/ # Just examples
        disable_ci_skip:         false      
      webhook_token:             ((token.webhook))
```

(Note: This resource is not a drop-in replacement for the `github-pullrequest-resource`)

**Comment by TG-KK** [comment]
@itsdalmo Sorry for delay! Here is the older config, where I get git exit 128 error:

```yaml
---
  resource_types:
    - name:                   pull-request
      type:                   docker-image
      source:
        repository:           teliaoss/github-pr-resource
        tag:                  latest
        registry_mirror:      https://docker.artifactory.mycompany.com


  resources:
    - name:                   pr-code
      type:                   pull-request
      source:
        repository:           my_org/code_repo
        access_token:         ((ci.personal_access_token))
        v3_endpoint:          https://github.mycompany.com/api/v3/
        v4_endpoint:          https://github.mycompany.com/api/graphql
      webhook_token:          ((token.webhook))


  jobs:
    - name:                   unit-tests
      max_in_flight:          3
      build_logs_to_retain:   5
      disable_manual_trigger: false
      plan:
      - get:                  pr-code
        trigger:              true
        params:
          version:            every
          fetch_merge:        true
      - put:                  pr-code
        params:
          path:               pr-code
          status:             pending
          context:            unit-tests
      - task:                 unit-test
        file:                 pr-code/ci/tasks/unit_test.yml
        input_mapping: {code_src: pr-code}
        params:
          ci.private_key:     ((ci.private_key))
          GITHUB_TOKEN:       ((ci.personal_access_token))
          SLACK_WEBHOOK_URL:  ((token.slack))
        on_success:
            put:              pr-code
            params:
              path:           pr-code
              status:         success
              context:        unit-tests
        on_failure:
            put:              pr-code
            params:
              path:           pr-code
              status:         failure
              context:        unit-tests
```

PR check goes fine:
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/6836944/45959746-3eae7400-bfe0-11e8-9a51-74d3fabfad69.png">

But, in the get step it fails:
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/6836944/45959812-5e459c80-bfe0-11e8-8a37-75584ed3cb95.png">
