### ISSUE TITLE
I am at odds on why it is not working. Help would be appreciated.

### ISSUE THREAD

**Issue by larssb** [telia-oss/github-pr-resource#48]
Hi there and thank you for making this resource for Concourse-CI.

I'm trying to get it to work and its giving me issues.

### INFO

My pipeline:

```yaml
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: pull-request
  type: pull-request
  source:
    access_token: ((github-access-token))
    disable_ci_skip: true
    repository: MyOrg/myrepo

jobs:
- name: myrepo
  plan:
  - get: pull-request
    trigger: true
    version: every
  - put: pull-request
    params:
      path: pull-request
      status: pending
  - task: npm-install
    config:
      platform: linux
      image_resource:
        source:
          repository: gcr.io/cloud-builders/npm
        type: docker-image
      inputs:
        - name: pull-request
      run:
        path: npm
        args: 
          - install
  - task: npm-test
    config:
      platform: linux
      image_resource:
        source:
          repository: gcr.io/cloud-builders/npm
        type: docker-image
      inputs:
        - name: pull-request
      run:
        path: npm
        args:
          - test
    on_failure:
      put: pull-request
      params:
        path: pull-request
        status: failure
  - put: pull-request
    params:
      path: pull-request
      status: success
```

- I'm running Concourse CI v4.2.1
- In Docker v18.06.1 for MacOS
- There is no errors when the `pull-request` is checking.
- I created a personal access token on a [machine account](https://developer.github.com/v3/guides/managing-deploy-keys/#machine-users) on GitHub
-- I even tried creating a new one, just to ensure I hadn't copied the first one correctly.
- I've been issuing pull requests like a mad man. None is being "caught" by the pull-request resource, by the `get` step.
- The user on which the personal access token has been configured, is a member of the organization and has write access to the repository on which I want Concourse CI to catch pull requests.
-- It's e-mail address has been verified on GitHub (a requirement for creating a token in the first place).

### ISSUE

Nothing happens when I create a pull request on 'x' branch to develop. Not on GitHub and not on Concourse CI.
Am I misunderstanding something in the way I have configured the pipeline? As far as I understand, I do not need to use a `webhook` for this. And a private key is not needed either.
The example by Stark and Wayne, found [here](https://github.com/starkandwayne/concourse-pullrequest-playtime) also do not use a webhook.

### OTHER

I'm trying to use this github-pr-resource as it seems to be the best one out there. And the `jtarchie/github-pullrequest-resource` directs to this one. [See](https://github.com/jtarchie/github-pullrequest-resource/issues/210).

----

I hope you can help me. Either with my understanding or if this is another issue, then with that.

Thank you so much and have a good one.
