### ISSUE TITLE
Getting commit sha from check

### ISSUE THREAD

**Issue by larssb** [telia-oss/github-pr-resource#51]
Hi I wondered if it is possible to get the commit sha that the check spits out. Mentioned here [check step](https://github.com/telia-oss/github-pr-resource#check).

Is that possible. I would like to use it as input for a docker image building step. To use it as the TAG.

Thank you.

**Comment by itsdalmo** [comment]
Hi! Currently the `get` step will write both the version object and everything you see in the [metadata](https://github.com/telia-oss/github-pr-resource/blob/master/in.go#L47-L52) to:
- `.git/resource/version.json`
- `.git/resource/metadata.json`


That files contents should look something like this:

```json
// version.json
{
  "pr": "4",
  "commit": "a5114f6ab89f4b736655642a11e8d15ce363d882",
  "committed":"0001-01-01T00:00:00Z"
}
// metadata.json
[
  {
    "name": "base_sha",
    "value": "<base-sha>"
  },
  ...
]
```

These are written to disk so that they can be reused in the `put` step, but are of course available to any task you have after the `get`. Would it be enough for you to use `jq` to fetch the SHA from one of these files?

**Comment by larssb** [comment]
Ok nice. Yeah jq is fine. Do you have a suggestion on the easiest way that I can use jq in a step. I've been through [community resources](https://concourse-ci.org/community-resources.html) and the [provided resources](https://concourse-ci.org/included-resources.html) there is none that seems to give me `jq` directly. So I guess the approach is to expand an docker-image I'm already using, in order to include jq in that?

Agree? Thank you.

**Comment by itsdalmo** [comment]
Yeah, we've ended up with some "toolbox" images that are used for generic tasks:
https://github.com/telia-oss/concourse-images/blob/master/awscli/Dockerfile

Not all too worried about ending up with a big image, since if it's used frequently enough it will always be cached on the workers anyway 🤷‍♂️

**Comment by haganbmj** [comment]
Here's an example of what I wound up doing to get the relevant information out of the resource.
I have it as an intermediary task step so that I can do other tasks without having to have a docker container with jq. I just needed a way to both get the commit sha for use with https://github.com/dpb587/github-status-resource and generate an identifier for how I push sonar results with https://github.com/cathive/concourse-sonarqube-resource

```yaml
- task: Write PR Number to File
  config:
    platform: linux
    image_resource:
      type: docker-image
      source: {repository: stedolan/jq, tag: "latest"}
    inputs:
      - name: pull-request
    outputs:
      - name: pull-request-flat
    run:
      path: /bin/sh
      args:
        - -xce
        - |
          cd pull-request
          cat .git/resource/version.json | jq -r '.pr' > ../pull-request-flat/id
          cat .git/resource/version.json | jq -r '.commit' > ../pull-request-flat/sha
          cat .git/resource/version.json | jq -r '[.pr,.commit] | "PR-\(.[0])-\(.[1])"' > ../pull-request-flat/pr-id
```
