### ISSUE TITLE
`check` step fails after upgrade from jtarchie/github-pullrequest-resource

### ISSUE THREAD

**Issue by willmurphyscode** [telia-oss/github-pr-resource#64]
I am building a new pipeline that needs to check GitHub pull requests. I had this portion working running with `jtarchie/github-pullrequest-resource`, but after switching to this pr resource, I am experiencing the following failure in the resource: 
```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
2019/01/03 02:03:13 failed to unmarshal request: json: unknown field "ref"
```
Running `fly check-resource` produces basically the same output.

I don't have any usual configuration at all, so I expected this to just work (after changing `repo` to `repository`). Here's my configuration for the resource:

``` yaml
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: cli
  type: pull-request
  check_every: 1m
  source:
    repository: cloudfoundry/cli
    access_token: ((github-access-token))
    ignore_paths:
    - README.md
    - .github/
```

The access token gets interpolated correctly, and has the following scopes:  `repo/repo:status` and `repo/public_repo`. The repository itself is public.

Any help would be appreciated. It seems to me that the `check` script is getting JSON back with an unexpected key, and I'm not sure how to address that. Has anyone seen this particular error message before?
