### ISSUE TITLE
stuck at preparing build

### ISSUE THREAD

**Issue by ClumsyPotato** [telia-oss/github-pr-resource#81]
Hey there,
as the title suggests my pipline is stuck at the preparing build stage. Following checks are pending

   - discovering any new versions of pull-request
   - waiting for a suitable set of input versions
       pull-request - no versions available

I am running concourse locally inside containers.
I already tried fly check-resource and check-resource-type and both only output "resource checked"-
the only purpose of my pipline is to try this resource so they isn't any big logic behind it.
and yeah my repo is public. 

No idea what the problem is :/

```

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: pull-request
  type: pull-request
  check_every: 24h
  webhook_token: ((token))
  source:
    repository: <user/reponame>
    access_token: ((tokken))
    # disable_ci_skip: true

jobs:
- name: test
  plan:
  - get: pull-request
    trigger: true
    version: every
  - put: pull-request
    params:
      path: pull-request
      status: success
      context: ci/cd
  - task: unit-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine/git, tag: "latest"}
      inputs:
        - name: pull-request
      run:
        path: /bin/sh
        args:
          - -xce
          - |
            cd pull-request
            git log --graph --all --color --pretty=format:"%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s" > log.txt
            cat log.txt








```
