### ISSUE TITLE
Enterprise git endpoint could not fetch commit 

### ISSUE THREAD

**Issue by ClumsyPotato** [telia-oss/github-pr-resource#82]
Hey there,

I am trying the use  git enterprise and get the following error when i execute fly -t <target> check-resource.

> 2019/02/26 18:05:38 check failed: failed to get last commits: invalid character '<' looking for beginning of value

```

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: pull-request
  type: pull-request
  check_every: 1m
  webhook_token: ((WEB_TOKEN))
  source:
    repository: org/repo
    v3_endpoint: https://<MY_HOST>/api/v3
    v4_endpoint: https://<MY_HOST>/api/v4
    access_token: ((ACCESS_TOKEN))
    skip_ssl_verification: true
```

Is something wrong the my v3_endpoint url?
I also tried it with just  `v3_endpoint: https://<MY_HOST>`
But that is just creating a mess
