### ISSUE TITLE
`get failed: exit status 128` when using `dev` tag

### ISSUE THREAD

**Issue by echarrod** [telia-oss/github-pr-resource#89]
I am getting `get failed: exit status 128` when trying to run a pipeline, the relevant parts of which are here:
```yaml
resource_types:
  - name: github-pr
    type: docker-image
    source: { repository: teliaoss/github-pr-resource, tag: "dev" }
    check_every: 720h

resources:
  - name: pr-src
    type: github-pr
    source:
      repository: myorg/myrepo
      access_token: ((my-access-token))

jobs:
  - name: pr-check
  plan:
      - get: pr-src
        trigger: true
        version: every
```

But the only output I'm getting is:
```
Initialized empty Git repository in /tmp/build/get/.git/
2019/03/21 12:14:37 get failed: exit status 128
```

I have made sure that the user associated with the access token has write permissions on the repo (not sure if this is actually needed)

I have looked through https://github.com/telia-oss/github-pr-resource/issues/35, which resulted in me attempting this with tags of: `v0.6.0`, `v11.0.0` and `dev`
