### ISSUE TITLE
Option to delete previously made comments on a pull request

### ISSUE THREAD

**Issue by rcoy-v** [telia-oss/github-pr-resource#95]
A use case we have is to make comments as a CI bot on a pull request, such as output of Terraform plan to know what will be applied if the pull request is merged.

Example pipeline snippet:
```
on_success:
      put: pull-request
      params
          path: pull-request
          status: success
          comment_file: github-comment/comment.txt
```

Comments can become outdated as changes are made to the pull request, since this verification runs on every commit. It would be nice to have a boolean option on `put` that would delete past comments made on the pull request by this resource. This would make sure only the latest information from CI is present on a pull request.

Example pipeline snippet:
```
on_success:
      put: pull-request
      params
          path: pull-request
          status: success
          comment_file: github-comment/comment.txt
          only_latest_comment: true
```

Wondering what thoughts are on a feature like this.
